parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../../../src/'

  App\Service\DevService:
    public: true
  App\Service\ServiceInterface: '@App\Service\DevService'